# Release branch validation configuration
# This file defines which JIRA numbers and authors can merge to release branches

# List of allowed JIRA numbers
# Use '*' to allow all JIRA numbers
# Or specify specific JIRA numbers, e.g.: ['ABC-123', 'DEF-456']
allowed_jiras:
  # - '*'  # Allow all JIRA numbers
  - 'ABC-123'
  - 'DEF-456'
  # - 'XYZ-789'

# List of allowed authors
# Use '*' to allow all authors
# Or specify specific GitHub usernames
allowed_authors:
  - '*'  # Allow all authors
  # - 'developer1'
  # - 'developer2'
  # - 'team-lead'

# Configuration instructions:
# 1. allowed_jiras: Define JIRA numbers that can be merged to release branches
#    - Use '*' to allow all JIRA numbers
#    - Or list specific JIRA numbers (format: PROJECT-NUMBER, e.g. ABC-123)
#
# 2. allowed_authors: Define authors that can merge to release branches
#    - Use '*' to allow all authors
#    - Or list specific GitHub usernames
#
# Notes:
# - Each commit message must contain at least one JIRA number
# - JIRA number format must be: UPPERCASE-NUMBER (e.g. ABC-123)
# - Validation will check both PR author and all commit authors