# Release branch validation configuration example
# This file shows how to configure specific JIRA numbers and author restrictions

# Example 1: Restrict specific JIRA numbers
allowed_jiras:
  - 'ABC-123'
  - 'ABC-124'
  - 'DEF-456'
  - 'XYZ-789'

# Example 1: Restrict specific authors
allowed_authors:
  - 'developer1'
  - 'developer2'
  - 'team-lead'
  - 'release-manager'

# Other configuration examples:

# Example 2: Only allow JIRA numbers from specific projects
# allowed_jiras:
#   - 'PROJ-*'  # Note: Current script doesn't support wildcards, need to list specific numbers

# Example 3: Mixed configuration
# allowed_jiras:
#   - 'HOTFIX-001'
#   - 'HOTFIX-002'
#   - 'RELEASE-001'
# 
# allowed_authors:
#   - 'senior-dev1'
#   - 'senior-dev2'
#   - 'devops-team'

# Usage instructions:
# 1. Rename this file to release-validation.yml
# 2. Modify allowed_jiras and allowed_authors according to project requirements
# 3. Commit to the .github/config/ directory of the repository