# Strict release branch validation configuration
# Used for testing specific JIRA numbers and author restrictions

# Only allow specific JIRA numbers
allowed_jiras:
  - 'PROJ-001'
  - 'DEMO-100'
  - 'TEST-002'

# Only allow specific authors
allowed_authors:
  - 'Test User'
  - 'test-user'
  - 'developer1'